- name: Install Python simplejson
  apt:
    pkg: python-simplejson
    state: present
    update_cache: true


- name: copy dump SQL file to tmp
  template:
    src: dump.sql
    dest: /var/tmp/


- name: Run SQL commands to delete existing databases
  mysql_db:
        login_host: "{{ wp_db_hostname }}"
        login_password: "{{ wp_db_password }}"
        login_user: "{{ wp_db_user }}"
        login_port: "3306"
        name: "{{ wp_db_name }}"
        state: absent

- name: Run SQL commands to delete existing databases
  mysql_db:
        login_host: "{{ pesbuk_db_hostname }}"
        login_password: "{{ pesbuk_db_password }}"
        login_user: "{{ pesbuk_db_user }}"
        login_port: "3306"
        name: "{{ pesbuk_db_name }}"
        state: absent

- name: Run SQL commands to create database {{ wp_db_name }}
  mysql_db:
        login_host: "{{ wp_db_hostname }}"
        login_password: "{{ wp_db_password }}"
        login_user: "{{ wp_db_user }}"
        login_port: "3306"
        name: "{{ wp_db_name }}"
        state: present


- name: Run SQL commands to create database {{ pesbuk_db_name }}
  mysql_db:
        login_host: "{{ pesbuk_db_hostname }}"
        login_password: "{{ pesbuk_db_password }}"
        login_user: "{{ pesbuk_db_user }}"
        login_port: "3306"
        name: "{{ pesbuk_db_name }}"
        state: present



- name: Deploy Database Dump SQL to remote server
  mysql_db:
        login_host: "{{ pesbuk_db_hostname }}"
        login_password: "{{ pesbuk_db_password }}"
        login_user: "{{ pesbuk_db_user }}"
        login_port: "3306"
        name: "{{ pesbuk_db_name }}"
        state: import
        target: "{{ target_dump }}"
