- name: Configure export bucket name
  shell: "kops export bucket_name= {{bucket_name }}"

- name: Configure export cluster name
  shell: "kops export kops_cluster_name= {{cluster_name }}"

- name: Configure export state store
  shell: "kops export kops_state_store= s3://{{bucket_name }}"

- name: Apply Ingress Mandatory 
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.27.1/deploy/static/mandatory.yaml
  
- name: Apply Ingress Service~14 
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.27.1/deploy/static/provider/aws/service-l4.yaml
  
- name: Apply Ingress ConfigMap
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.27.1/deploy/static/provider/aws/patch-configmap-l4.yaml


